import { Geist, Geist_Mono, Open_Sans } from "next/font/google";
import "./globals.css";
import ApolloProviderWrapper from "@/providers/ApolloProvider";
import { ToastContainer } from "react-toastify";

const openSans = Open_Sans({
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "600", "700"],
  variable: "--font-open-sans",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${openSans.variable}`}>
        <ApolloProviderWrapper>
          {children}
          <ToastContainer />
        </ApolloProviderWrapper>
      </body>
    </html>
  );
}
